### PR TITLE
WIP: More Validation

### PR DESCRIPTION
**Pull request by odscjames**
For #92

Adds
- must have category
- must have core
- core must be ["true", "false", "True", "False"]
- MORE TO ADD, WIP

Also improves validate errors - shows you extension id in each one.

### CODE REVIEW

**Comment by jpmckinney** [comment]
Looking good so far! I think we can just have one pair of true/false or True/False. I prefer lowercase, but you can choose whichever. We can also then remove `string_to_boolean`.

I'll wait for other commits before reviewing.

**Comment by odscjames** [comment]
Let's go with True/False simply because that's what was already used. Have a look now!

**Comment by jpmckinney** [comment]
* Can you fill in the `enum` for `category`?
* Can the categories be read from that enum rather than from `categories.csv`?
* The JSON Schema should have `"additionalProperties": false`
* Can we relax `repository_url` to be just `"format": "uri"` instead of a specific pattern?
* The `pattern` for `id` should use `+` instead of `*` as it should be at least one character. I also don't anticipate numbers in `id`, at present.

**Comment by odscjames** [comment]
> Can you fill in the enum for category?
> Can the categories be read from that enum rather than from categories.csv?

(I'm making the assumption here that the categories aren't fixed and might be edited - let me know if that's a bad assumption.)

It seems better to leave them in a separate spreadsheet? I think it's important to make sure that the data is easy to edit for people with little technical knowledge, and having a simple self contained file is better than having something embedded in the tool. That would require more knowledge to work with, and in some ways constrain our ability to change in the future. I think as long as we have automated tests to show the tool is working and thus people can have confidence in it, the inner workings of the tool should be a bit of a "black box" to non-technical editors. 

Was there a particular reason behind this request?

> The JSON Schema should have "additionalProperties": false

Sure, tho as the JSON  is generated from the Python this should be impossible :-)

> Can we relax repository_url to be just "format": "uri" instead of a specific pattern?

No - we do need to validate it's a GitHub URL at the moment. The tools needs some knowledge to convert from https://github.com URLs to https://raw.githubusercontent.com/ URLs (See ExtensionForStandardVersion class in models.py). As said before, we can add GitLab and BitBucket support pretty easily if wanted but the tools do need to know, and thus we need it validated.

> The pattern for id should use + instead of * as it should be at least one character. I also don't anticipate numbers in id, at present.

Do you object to leaving numbers in? It seems like something that is normal for Ids and could easily happen in the future.

Will do the one character thing, others and fix merge conflicts soon.

**Comment by jpmckinney** [comment]
The categories are primarily used to make extensions appear in specific places in the documentation; as such, they are fairly stable. I don't know who these non-technical editors of the registry's schema are; that's not a requirement we need to satisfy for managing the list of categories. I think having most validations expressed in a single JSON Schema file is simpler and smaller than having the information necessary to perform validations split across a CSV and JSON.

I know that the code doesn't presently support non-GitHub (which is something I'll think more about soon), but I don't want to create the perception that non-GitHub extensions are officially unsupported. If the code breaks once someone submits a non-GitHub extension, that's a good trigger for us to get on with implementing non-GitHub support.

As I can't imagine a situation in which a number would make sense for an extension's ID, I think it makes most sense to exclude it until such time that we can reasonable expect numbers.

**Comment by odscjames** [comment]
Quick reply; 

> I know that the code doesn't presently support non-GitHub (which is something I'll think more about soon), 

I can easily add GitLab and BitBucket if wanted and we already have a ticket to support non-git hosted repos so I think that is in progress.

> but I don't want to create the perception that non-GitHub extensions are officially unsupported. If the code breaks once someone submits a non-GitHub extension, that's a good trigger for us to get on with implementing non-GitHub support.

I really think this should validate GitHub. The https://github.com/open-contracting/extension_registry/blob/master/README.md file explains the GitHub situation at the moment, so hopefully people won't be confused. 

And if we just remove the GitHub validation and do nothing else, then bad URL's will be built - essentially, there will be a confusing weird error later in the process that the person adding extensions may not even notice. I think it would be much better to have a nicer error message earlier on in the process.

**Comment by jpmckinney** [comment]
Good points - I'll try to avoid weird errors in my future changes. I'll merge this in now and pursue some of the comments in a new PR.

**Pull request merged**
