### PR TITLE
Travis - add comments and work to file

### PR DESCRIPTION
**Pull request by odscjames**
This is a continuation of P.R. #93 - due to the merge to master that branch needed to be rebased in some way. (If there is a cleverer way of doing that with GitHub P.R.'s sorry!)

I have a little more coding I want to do on this then I will comment fully.

### CODE REVIEW

**Comment by odscjames** [comment]
sudo: false isn't required any more - it's now the default. https://docs.travis-ci.com/user/reference/overview/ We could maybe do sudo: false and dist: trusty to lock us to the current platform for when Travis release a new platform, but in the past they've been very good at not bumping people up without tons of warning so I think it's fine.

The deploy stuff I would prefer to leave out - it's in version control and it's not lost, and there's a comment to make sure it's not forgotten. I think it's standard advise in programming not to leave commented out code as this can often end up confusing people later with whether it's relevant or not. Also it might mislead people that they can just comment it back in and it'll work - in reality small changes to open-contracting-extension_registry-deploy.sh will be needed to cope with the change from many Travis branches to one. Hopefully the comment I wrote already makes things clear enough to people that are reading later - what do people think?

Hope you don't mind me picking over this like this - it's a great way for me to learn what's currently happening with all this work which really helps!

**Comment by odscjames** [comment]
> We can add setup.cfg, though I prefer to leave it out; we presently use the same flake8 config in all repos,

Is there a central place that someone would be reasonably expected to find that? I guess I put that in here to reduce knowledge required for someone to start work and reduce things to check while working. Tho I can see the potential for drift between repos the potential for drift between different developers seems worse. Tho it is in Travis so maybe it's not important; it will be caught. Hmmmm.

> Do we want to be caching extension repositories? I forget in what scenarios they get expired.

I think so, if we didn't we'd have to do a full clone of each repository each time. This way we can do a "git pull" instead which is faster and less bandwidth. Travis might expire them or also in some cases it might use them but not write changes back afterwards for security reasons - in either case it doesn't matter to much. This code will do a "clone" or "pull" as needed and I can't forsee any issues.

> Also, why the explicit pip path instead of pip?

Only cos I couldn't make

```
cache:
    - pip
   directories:
       - extensions_repositories
```

work as valid YAML - if you can do correct me :-)

**Comment by jpmckinney** [comment]
In an operational context in which teams work on a small set or family of repositories, or in which repositories are not integrated or inter-dependent, individual configurations make sense. Our circumstances are of having very few people working across very many repositories, most of which are integrated or inter-dependent (e.g. I work across all extensions, which have the same setup). So, in that context, it's beneficial to have centralize quality assurance even at the expense of additional startup cost. I have Rake tasks to ensure correct repository configuration, e.g. all repos running the central QA scripts and having Travis set-up.

I just read the Travis docs, which include under [Things not to cache](https://docs.travis-ci.com/user/caching/#Things-not-to-cache):

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source

See more under [How does caching work?](https://docs.travis-ci.com/user/caching/#How-does-caching-work%3F). Given that extensions are static files with no installation time, I figure they are not appropriate to cache. (Granted, most Python packages are quick to install, but some like lxml are not, so we just always cache Python packages regardless of install time vs. download time.)

**Comment by odscjames** [comment]
Fair enough about caching. I'm not sure how much processing git does but with only a small number of repos at the moment and each repo being tiny it probably isn't a good use of our time to get into measuring it to work out which is better, so I'll just take it out. 

I've taken out setup.cfg for now then - would be an interesting discussion for later but this P.R. is already doing several things at once and it would be good to merge it in!

Have a look now.

**Comment by jpmckinney** [comment]
Looks good, thanks!

**Pull request merged**
