### PR TITLE
Work on new extension registry

### PR DESCRIPTION
**Pull request by odscjames**
Hello,

I’ve pushed work to a new branch here.

This creates a single branch and a single CSV, and de-duplicates a lot of data between the extension registry and extension repositories.

It has a “validate.py” that checks the contents of the CSV.

It has a new “compile.py”, which when run makes several directories:
* output - folder containing the complete data that is written 
* legacy_output - folder containing output data in the same format as the old version, for Sphinx.
* extensions_repositories - has the checkouts of the extension repos in it - needed to access various bits of info.
 
There are examples of these online so you can see them without having to run it yourself:
* https://github.com/odscjames/ocer-demo/tree/master/extension_registry/legacy_output
* https://github.com/odscjames/ocer-demo/tree/master/extension_registry/output

The actual working code is broken into a separate package for cleanness and reuse and there are pytest tests.

As you can see the extensions.csv only has a few columns in.

* Id
* Category
* RepositoryURL
* Core

All other data is taken from the extension.json in the extension repository. Eg

* Name
* Description
* Compatibility
* Documentation URL

To avoid duplication of data, we are deliberately not keeping data in both.

We could move category and core back to the extension repositories or move some of the other fields from the extension repositories back into the main csv. While thinking about any such moves, the considerations should be:
* Is this bit of data something that extension authors should be able to update with no oversight from the registry, or do we want any changes to this data to be  approved by the registry first? (eg “Core” is in the extensions.csv because an extensions author should not be able to promote their community extension to core without oversight!)
* where data currently lives and hence what is easier to deploy (eg “category” is in the extensions.csv because it’s not in any extensions repositories currently - so to move it there would involve editing every repository!)
* think about when a new version of the standard is released - what can we do to make tagging/releasing new versions of each extension for that as easy as possible

Other notes
* The old version had an active flag in it. As far as I can tell, this is not used at all. I ignored it.
* Unfortunately, during the time when the data was duplicated there has been some drift between the 2 places. (Eg documentation_details is named “Document Details” in the extension repository but “Documentation” in the registry repository.) So some checking will be required to look out for things like that, and to re-edit anything that was previously edited in the wrong place.
* It currently only support GitHub - because it needs to change URLs into different forms. But it would be easy to add GitLab or Bitbucket.
* It currently has a stripped down .travis-ci while we discuss this - so no danger of it deploying!
* Also a stripped down Readme - I can build that up later again.

What do people think?

Thanks,
James

### CODE REVIEW

**Comment by jpmckinney** [comment]
This looks like a great first iteration, though we may continue to tweak as we work through how this change affects code depending on the registry. A few requests:

* Could you compare names and descriptions, so that we can see the drift, and make changes to extensions if appropriate? I imagine you can output a CSV or other document showing differences.
* We can test the CSV using JSON Schema. See [this test for codelist files](https://github.com/open-contracting/standard-maintenance-scripts/blob/61bffe3ee0b4f991bca80cb568b73c5eb37faba0/tests/test_csv.py#L113).
* Could you restore the removed .travis.yml content, but comment it out instead? That way, we're less likely to forget to add it back :)
* Could you add to the readme a description of the extensions.csv headers?

Other notes:

* I prefer to have centralized control of `category` as it affects where extensions appear in the documentation (via the `extensionlist` Sphinx directive).
* Regarding "what can we do to make tagging/releasing new versions of each extension for that as easy as possible", I have [Rake tasks](https://github.com/open-contracting/standard-maintenance-scripts#prepare-for-a-release-of-ocds) to help with that :)
* The active flag is indeed unused.

In terms of the CSV's schema:

The new extensions.csv works for repositories whose releases (versions) can be determined via the version control system. However, extensions are allowed to be uploaded to e.g. an FTP server (imagine a folder of ZIP files for `extensionA.1.0.zip`, `extensionA.1.1.zip`, `extensionB.1.1.zip`, etc.) One solution is for each row of the CSV to be a release, rather than an extension; the URL would have to point to the specific release, and a Version column would have to be added for the version number. This would cause repetition of Id, Category, and Core across releases of a single extension. To address that, we can either add a consistency test, or have Id, Category and Core in one file, and Id, URL and Version in another file. The first file would be managed by standard authors who decide the Category and Core, whereas the management of the second file could be more distributed, as it will pretty much only be appended to via PR by extension authors.

The new output files have columns for each release of the standard for which there are extensions released. While core extensions follow the standard's versioning, community extensions can use any version numbers they like. They can have a 1.1.3-alpha, 1.1.3-rc.1, 5.3, 11 – anything, really. So, we may need to, as above, have one release per row. This will duplicate some information, but as this file is generated, that duplication won't come with data integrity risks.

What do you think?

**Comment by odscjames** [comment]
> This looks like a great first iteration, though we may continue to tweak as we work through how this change affects code depending on the registry. 

Is there other bits of code I should look at that will depend on this? (I’ve looked at the existing Sphinx docs already.)

> A few requests:
> Could you compare names and descriptions, so that we can see the drift, and make changes to extensions if appropriate? I imagine you can output a CSV or other document showing differences.

I can make a report on what the differences are, but I’m not sure I can fix them - I might not have enough knowledge to know what the correct one will be when faced with 2 choices. But I can certainly make a report and put it in another issue.

> We can test the CSV using JSON Schema. See this test for codelist files.

That’s an interesting technique - I will consider where we can use that, thanks.

> Could you restore the removed .travis.yml content, but comment it out instead? That way, we're less likely to forget to add it back :)

I will have to have some discussion with people here to work out best way to deploy (due to the change from many branches to one), but I can do that.

> Could you add to the readme a description of the extensions.csv headers?

Will do.

>Other notes:
> I prefer to have centralized control of category as it affects where extensions appear in the documentation (via the extensionlist Sphinx directive).
> Regarding "what can we do to make tagging/releasing new versions of each extension for that as easy as possible", I have Rake tasks to help with that :)
> The active flag is indeed unused.

All good, thanks! Curious to look more into new version situation later.

> In terms of the CSV's schema:
> The new extensions.csv works for repositories whose releases (versions) can be determined via the version control system. However, extensions are allowed to be uploaded to e.g. an FTP server (imagine a folder of ZIP files for extensionA.1.0.zip, extensionA.1.1.zip, extensionB.1.1.zip, etc.) 

Am I right in thinking this isn’t currently used? Is anyone about to use this scheme? Are there details of exactly how this scheme would work somewhere I can read? (For example, my first thought is would it support ZIP files being on HTTP(S) servers - I would have thought these days that’s more likely than FTP.)

(To be totally honest, if this isn’t something that is already in high demand I’d maybe try and backpedal on this and just encourage people to use GitHub, GitLab, BitBucket, etc. The reason is that that you way you get higher transparency and traceability. Someone could change an ZIP file contents easily where as if it’s in Git there’s a measure of protection against that. It’s also easier for a casual browser to look into an extension and see what’s inside. Also, if someone is making a lot of releases you want to encourage them to be using version control behind the scenes anyway so just make them put up a repository! But that’s probably a totally different discussion and if this is already used we of course have to support it.) 

But generally, I note that this already supports 2 versioning schemes so making it flexible to support different schemes should be fine.

> One solution is for each row of the CSV to be a release, rather than an extension; the URL would have to point to the specific release, and a Version column would have to be added for the version number. This would cause repetition of Id, Category, and Core across releases of a single extension. To address that, we can either add a consistency test, or have Id, Category and Core in one file, and Id, URL and Version in another file. The first file would be managed by standard authors who decide the Category and Core, whereas the management of the second file could be more distributed, as it will pretty much only be appended to via PR by extension authors.

I would favour the second file approach - have a “extensionversions.csv” with columns like Id, Version, Reference.  

I think the problem you identify of repetition is an important one to avoid. Also this way, the number of columns that might not be relevant is reduced which makes for files that are easier to edit. And as you note, different people will tend to be editing different files so that cuts down on possible conflicts.

> The new output files have columns for each release of the standard for which there are extensions released. While core extensions follow the standard's versioning, community extensions can use any version numbers they like. They can have a 1.1.3-alpha, 1.1.3-rc.1, 5.3, 11 – anything, really. So, we may need to, as above, have one release per row. This will duplicate some information, but as this file is generated, that duplication won't come with data integrity risks.

So one advantage of this approach generally is that we can have multiple files output for different use cases.

(One thing to be careful of if is that there are 2 different situations with regards to versions:

* Core package versions are locked to standard versions, so for any one standard version there is only one extension version.
* Community packages can release whenever and could have several different versions for one standard version.

So when you say “one release per row” we just have to be careful to be clear whether we mean “one standard release per row” or “one extension release per row” as these could be different.)

So maybe we could have “data.en.csv”, pretty much the same as “full_data.en.csv” is now - because I would guess a file with one row per extension is a good starting point for new people.

Then a file “data_versions.en.csv” with one row per extension version. 

Also, have “data_versions.standard_X.X.X.en.csv” with one row per extension version, but only the ones that are applicable to that standard version. I would guess someone saying “I’m using standard X.X.X, what extensions can I use with that?” would be a very common question and now there is one file they can look at to see.


> What do you think?

Thank you for the comments! I don’t work on mondays but I will prioritise the points identified above for the rest of next week.

**Comment by jpmckinney** [comment]
> Is there other bits of code I should look at that will depend on this? (I’ve looked at the existing Sphinx docs already.)

You can follow the trail of references to `extension_registry_git_ref` in sphinxcontrib-opencontracting, documentation-support, standard_profile_template, standard and profiles

> I can certainly make a report and put it in another issue.

Great, thanks!

> I would favour the second file approach - have a “extensionversions.csv” with columns like Id, Version, Reference.

Sounds good! (And I mean "one extension release per row".)

Regarding the output files:
* The legacy files for released versions of OCDS are already built and deployed at e.g. http://standard.open-contracting.org/extension_registry/v1.1.1/ so we don't necessarily need to be able to regenerate them. We should preserve the building and deployment of new legacy-style files (`legacy_output`), until we change the code depending on those legacy-style files.
* We don't necessarily need the new output files (`output`), as users are not expected or directed to interact directly with this repository. The extensions documentation website is where we will answer questions like "What extensions are compatible with this version of OCDS?" etc.

Regarding the extension mechanism more generally, here's our [extension mechanism design documentation[(https://docs.google.com/document/d/1zV0_UeVTGEdLRq5DQEH3XAUWl0HrHNNQPEwftLkHqBQ/edit). @kindly was most involved in the design. We can discuss further (e.g. how to best ensure integrity, whether to specify the protocols to use), but those discussions don't immediately impact this issue, I think.

**Comment by odscjames** [comment]
> Could you add to the readme a description of the extensions.csv headers?

Done

> Could you compare names and descriptions, so that we can see the drift, and make changes to extensions if appropriate? I imagine you can output a CSV or other document showing differences.

Done in #91

> Is there other bits of code I should look at that will depend on this? (I’ve looked at the existing Sphinx docs already.)
> You can follow the trail of references to extension_registry_git_ref in sphinxcontrib-opencontracting, documentation-support, standard_profile_template, standard and profiles

I have started looking at these and I will carry on checking the rest.

> Could you restore the removed .travis.yml content, but comment it out instead? 
> Regarding the output files:
> The legacy files for released versions of OCDS are already built and deployed at e.g. http://standard.open-contracting.org/extension_registry/v1.1.1/ so we don't necessarily need to be able to regenerate them. We should preserve the building and deployment of new legacy-style files (legacy_output), until we change the code that depends on those legacy-style files.

So to be clear; for the existing standard versions (1.1.3, 1.0.3, 1.0.0) we don’t actually want the extensions data in those versions to change? So we don’t need to upload legacy data files for those versions? 

If so, the current travis.yml is good. But in preparation for future work I have checked Travis can build the new data files fine, and cache the extension repositories. I added commments back to the config file and this can be seen at https://github.com/open-contracting/extension_registry/blob/new_extension_registry_travis/.travis.yml It’s in a new branch - I can copy it to this P.R. if that’s good.

> We don't necessarily need the new output files (output), as users are not expected or directed to interact directly with this repository. The (future) extensions documentation website is where we will answer questions like "What extensions are compatible with this version of OCDS?" etc. We can pause development around those files for now.

Ok.

> Regarding the extension mechanism more generally, here's our extension mechanism design documentation. @kindly was most involved in the design. We can discuss further (e.g. how to best ensure integrity, whether to specify the protocols to use), but those discussions don't immediately impact this issue, I think.

That was good background, thanks. I don’t see anything that contradicts this tho. 

Is there anything else we need to consider? I will keep checking the repos listed.

**Comment by jpmckinney** [comment]
All looks good!

* Please create a PR for new_extension_registry_travis branch. I may want to restore some other bits of the [old .travis.yml](https://github.com/open-contracting/extension_registry/pull/90/files#diff-354f30a63fb0907d4ad57269548329e3).
* Please also create an issue about validation, to pursue the JSON Schema-based validation idea above (likely restoring parts of entry-schema.json as part of that).

> So to be clear; for the existing standard versions (1.1.3, 1.0.3, 1.0.0) we don’t actually want the extensions data in those versions to change? So we don’t need to upload legacy data files for those versions?

That's right - published versions don't change. (We sometimes make copy-edits or HTML fixes to the most recently deployed version, but to my knowledge we haven't gone back to fix old versions.)

**Comment by jpmckinney** [comment]
Okay to merge, so that we can continue on other PRs?

**Comment by odscjames** [comment]
Merged - Thanks, and to David for the code review. I will continue on other P.R.s

**Pull request merged**
